# Generated by Django 5.1.3 on 2024-12-13 17:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Collector1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_info', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='payment',
            name='accountNUMBER',
        ),
        migrations.RemoveField(
            model_name='collector',
            name='user',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='collector',
        ),
        migrations.RemoveField(
            model_name='supplies',
            name='collector',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='item',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='items',
            name='userN',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='item',
        ),
        migrations.RemoveField(
            model_name='supplies',
            name='ItemName',
        ),
        migrations.RemoveField(
            model_name='supplies',
            name='item1',
        ),
        migrations.RemoveField(
            model_name='supplies',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='Transaction',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='userN',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='userN',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='userName',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user',
        ),
        migrations.RemoveField(
            model_name='users',
            name='userrole',
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default='mukuri@gmail.com', max_length=254, validators=[django.core.validators.EmailValidator()]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='NameCollector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ItemNam', to='myapp.collector1'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WasteSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='waste_images/')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('NameCollector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.collector1')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=255)),
                ('waste_submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.wastesubmission')),
            ],
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Collector',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.DeleteModel(
            name='Supplies',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]


migrations.AddField(
    model_name='Users',
    name='id',
    field=models.IntegerField(default=1),  # Problematic
),
 
