# Generated by Django 5.1.3 on 2024-12-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_category_collector1_remove_payment_accountnumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecyclingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField()),
                ('button_text', models.CharField(max_length=100)),
                ('button_description', models.TextField()),
            ],
        ),
    ]
