# Generated by Django 5.1.3 on 2024-12-14 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_recyclinginfo1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastesubmission',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.category'),
        ),
    ]
