# Generated by Django 5.1.3 on 2024-12-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_wastesubmission_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastesubmission',
            name='latitude',
            field=models.FloatField(default=-1.9441),
        ),
        migrations.AlterField(
            model_name='wastesubmission',
            name='longitude',
            field=models.FloatField(default=30.0619),
        ),
    ]
