# Generated by Django 5.1.3 on 2024-12-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_paymentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector1',
            name='email',
            field=models.EmailField(default='thierry@gmail.com', max_length=255, unique=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collector1',
            name='password',
            field=models.CharField(default='123', max_length=128),
            preserve_default=False,
        ),
    ]
