# Generated by Django 5.1.3 on 2024-12-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_collector1_email_collector1_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastesubmission',
            name='status',
            field=models.CharField(default='Pending', max_length=26),
        ),
    ]
