# Generated by Django 5.1.3 on 2024-12-18 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_payment1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment1',
            name='collector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collector_payment', to='myapp.users'),
        ),
    ]
